export const dataSites = {
  1: {
    title: 'Інтернет Провайдер "Вектор"',
    url: 'vector',
    link: 'https://link for site Vector',
    technology: 'WordPress',
    description: [
      "Наш редизайн сайту — це свіжий подих та сучасний образ. Ми перетворимо ваш існуючий веб-сайт у вражаючий, сучасний та функціональний інтерфейс, який залучатиме та залишиться у пам\'яті відвідувачів.",
      "Ми звернемо особливу увагу на візуальний аспект: ми покращимо дизайн, розміщення контенту та колірну палітру, щоб забезпечити приємний та захоплюючий вигляд. Адаптивний дизайн гарантуватиме, що ваш сайт виглядає і працює ідеально на будь-якому пристрої, від мобільних телефонів до настільних комп'ютерів.",
      "Ми покращимо взає4модію з відвідувачами, розробивши зручний та логічний інтерфейс. Навігація стане більш зрозумілою, а інформація легко доступною.",
      "Крім того, ми забезпечимо вас сучасними функціями та можливостями. Ваш сайт буде підтримувати інтерактивність, швидкість завантаження та оптимізацію для пошукових систем.\n",
      "Наша мета — зробити ваш сайт не тільки красивим, а й ефективним інструментом для досягнення ваших цілей.",
      "Перший скріншот - сайт до перевтілення;",
      "Другий і третій скріншот - сайт після редизайну",
    ],
    externalScreenshot: './images/vector/main.jpg',
    screenshotsIn: [
      '/images/vector/old-design.jpg',
      '/images/vector/new-design.jpg',
      '/images/vector/form.jpg',
    ],
  },
  2: {
    title: 'Vector2',
    url: 'vector2',
    link: 'https://link for site2',
    technology: 'WordPress',
    description: ['eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaergeragaerg eragaerg'],
    externalScreenshot: './images/vector/main.JPG',
    screenshotsIn: [
      '/images/vector/old-design.JPG',
      '/images/vector/new-design.JPG',
      '/images/vector/form.JPG',
    ],
  },
  3: {
    title: 'Rector',
    url: 'rector',
    link: 'https://link for site3',
    technology: 'React',
    description: ['eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaergeragaerg eragaerg'],
    externalScreenshot: './images/vector/main.JPG',
    screenshotsIn: [
      '/images/vector/old-design.JPG',
      '/images/vector/new-design.JPG',
      '/images/vector/form.JPG',
    ],
  },
  4: {
    title: 'Rector',
    url: 'rector',
    link: 'https://link for site3',
    technology: 'React',
    description: ['eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaerg eragaerg eragaerg eragaerg eragaerg eragaerg eragaerg vv eragaergeragaerg eragaergeragaergeragaerg eragaerg'],
    externalScreenshot: './images/vector/main.JPG',
    screenshotsIn: [
      '/images/vector/old-design.JPG',
      '/images/vector/new-design.JPG',
      '/images/vector/form.JPG',
    ],
  },
}